export const DATA_LIST = [
  {
    imgborder: "#3E2A18",
    boxborder: "#3E2A18",
    background: "#FFF8E2",
    shadow: "#573f36",
    color: "#6F5246",
    image: "/Token_Nft/vote.png",
    title: "UCC Polling",
    desc: "Sheep will be released seasonally, and users will be able to submit direct designs and nominations for sheep to be released. The vote of the NGIT holders determines which sheep are chosen from the nominations.",
  },
  {
    imgborder: "#3E2A18",
    boxborder: "#3E2A18",
    background: "#FFF8E2",
    shadow: "#573f36",
    color: "#6F5246",
    image: "/Token_Nft/storm.png",
    title: "DAO Gaming",
    desc: "User votes can influence a variety of aspects. For example, depending on the outcome of the vote, the weather could be either dry or rainy. Some sheep do well in dry weather, while others may be more productive in humid conditions.",
  },
  {
    imgborder: "#3E2A18",
    boxborder: "#3E2A18",
    background: "#FFF8E2",
    shadow: "#573f36",
    color: "#6F5246",
    image: "/Token_Nft/dao.png",
    title: "Defi Staking",
    desc: "Holders of NGIT tokens are deemed to be making a contribution to the Sheepfarm ecosystem simply by holding their tokens. If you stake NGIT, you can receive MARD tokens as a reward.",
  },
];
