export const DATA_LIST = [
  {
    imgborder: "#6f5246",
    boxborder: "#ecc66a",
    background: "#ffec9e",
    shadow: "#e8dcb5",
    color: "#6f5246",
    image: "/Token_Nft/harvest.png",
    title: "Sell Wool",
    desc: "Raise sheep and shear their wool! Rare sheep breeds are known for producing high-valuable wool. The wool you sheared can be delivered to the village chief who will then reward you with MARD.",
  },
  {
    imgborder: "#6f5246",
    boxborder: "#ecc66a",
    background: "#ffec9e",
    shadow: "#e8dcb5",
    color: "#6f5246",
    image: "/Token_Nft/sell_sheep.png",
    title: "Rent out sheep",
    desc: "Instead of managing their NFTs personally, pasture or sheep owners can make a profit by renting them out. Users who are more interested in NFT investment rather than management may find this feature handy.",
  },
  {
    imgborder: "#6f5246",
    boxborder: "#ecc66a",
    background: "#ffec9e",
    shadow: "#e8dcb5",
    color: "#6f5246",
    image: "/Token_Nft/pvp_win.png",
    title: "Compete with others",
    desc: "Take part in a friendly competition with other users. Because it is difficult to outperform other players, the prize will be substantial. Outstanding players can easily obtain MARD by participating in PvP content.",
  },
];
